2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:25 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-05 23:32:31 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoogleTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-02-05 23:32:32 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-05 23:32:32 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][0]['platform']. Got None. (See ?, line ?). 
2022-02-05 23:32:33 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-05 23:32:36 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2022-02-05 23:32:36 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2022-02-05 23:32:47 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:32:48 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:02 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:02 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:02 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 80adf825ef6b969ee3c95fc54091652f8a80fe790532f31c6bff63908742af08 from 192.168.86.28
2022-02-05 23:33:19 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff711db0a0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:20 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:21 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-05 23:33:24 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_plafond: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-05 23:33:24 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_plafond: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-05 23:33:24 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_staande_lamp: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-05 23:33:24 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_staande_lamp: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-05 23:33:24 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2022-02-05 23:33:25 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-05 23:33:25 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-05 23:33:25 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-05 23:33:25 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-05 23:33:25 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-05 23:33:26 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-05 23:33:27 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 186, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 199, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 167, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2022-02-05 23:33:30 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2022-02-05 23:33:30 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:33:35 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] support_preheater set to False: 502
2022-02-05 23:33:35 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.
2022-02-05 23:33:35 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up audiconnect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.
2022-02-05 23:33:57 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2022-02-05 23:33:57 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2022-02-05 23:34:02 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-05 23:34:02 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:34:02 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2022-02-05 23:34:02 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2022-02-05 23:34:04 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:34:06 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-05 23:34:08 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:34:28 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:34:38 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:41:03 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:42:48 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:43:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.

2022-02-05 23:43:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_user_reset. State max length is 255 characters.

2022-02-05 23:43:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_data. State max length is 255 characters.

2022-02-05 23:43:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_data. State max length is 255 characters.

2022-02-05 23:51:28 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-05 23:53:37 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.

2022-02-05 23:53:37 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_user_reset. State max length is 255 characters.

2022-02-05 23:53:37 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_data. State max length is 255 characters.

2022-02-05 23:53:37 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_data. State max length is 255 characters.

2022-02-06 00:00:18 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-06 00:00:25 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-06 00:03:38 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-06 00:03:39 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.

2022-02-06 00:03:39 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_user_reset. State max length is 255 characters.

2022-02-06 00:03:39 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_data. State max length is 255 characters.

2022-02-06 00:03:39 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_data. State max length is 255 characters.

2022-02-06 00:13:40 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_user_reset. State max length is 255 characters.

2022-02-06 00:13:40 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_user_reset. State max length is 255 characters.

2022-02-06 00:13:40 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_longterm_trip_data. State max length is 255 characters.

2022-02-06 00:13:40 ERROR (MainThread) [homeassistant.util.logging] Exception in async_schedule_update_ha_state when dispatching 'audiconnect.updated': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 685, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1045, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.audi_e_tron_sportback_55_shortterm_trip_data. State max length is 255 characters.

2022-02-06 00:17:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.veranda_speaker_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 512, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 716, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 228, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 234, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 143, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 76, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
