2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-10 22:20:08 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff90a51b50>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:20:11 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-10 22:20:11 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-10 22:20:12 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-10 22:20:12 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-10 22:20:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-11-10 22:20:16 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2021-11-10 22:20:17 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-11-10 22:20:17 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-11-10 22:20:17 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2021-11-10 22:20:19 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-11-10 22:20:20 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff8c5c1700>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-11-10 22:20:26 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-10 22:20:26 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-10 22:20:27 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the douche bulb in the Philips Hue App.
2021-11-10 22:20:28 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2021-11-10 22:20:28 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.tv_energy
2021-11-10 22:20:29 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-10 22:20:30 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:20:30 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-11-10 22:20:32 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 166, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 179, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 155, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-11-10 22:20:34 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:20:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-10 22:21:01 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:21:05 WARNING (stream_worker) [libav.hls] skipping 1 segments ahead, expired from playlists
2021-11-10 22:21:13 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6ada7130>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:21:16 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-11-10 22:21:16 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-10 22:21:16 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-10 22:21:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-10 22:21:16 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:21:16 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-10 22:21:18 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:21:18 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:21:43 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:21:58 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:22:16 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff7c75adc0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:22:38 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:22:38 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:22:38 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:22:39 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:23:06 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:23:07 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:23:16 ERROR (SyncWorker_11) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff7c520fa0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:23:36 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-10 22:23:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.precip_rate_leuven24_wunderground is taking over 10 seconds
2021-11-10 22:23:45 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: https://www.wunderground.com/dashboard/pws/ILEUVE24 failed with 
2021-11-10 22:23:45 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to retrieve data for precip_rate_leuven24_wunderground
2021-11-10 22:24:16 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff8935d880>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:24:32 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for humidity_leuven24_wunderground
2021-11-10 22:24:32 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for temp_leuven24_wunderground
2021-11-10 22:25:16 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff79e9f550>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:26:16 ERROR (SyncWorker_8) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff79e85700>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:26:35 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for precip_rate_leuven24_wunderground
2021-11-10 22:26:53 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2021-11-10 22:27:16 ERROR (SyncWorker_12) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6b06f8e0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:27:25 WARNING (stream_worker) [libav.hls] skipping 1 segments ahead, expired from playlists
2021-11-10 22:27:36 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2021-11-10 22:28:16 ERROR (SyncWorker_19) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6b024460>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:28:32 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for humidity_leuven24_wunderground
2021-11-10 22:28:32 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for temp_leuven24_wunderground
2021-11-10 22:29:16 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff7a597b20>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:30:16 ERROR (SyncWorker_12) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6a3b9040>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:31:16 ERROR (SyncWorker_18) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff8c2ce580>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:32:16 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6a164340>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:32:34 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-10 22:33:16 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff69173fd0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:34:16 ERROR (SyncWorker_18) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff690fbdc0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:35:16 ERROR (SyncWorker_11) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff6a2b41f0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-10 22:35:43 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-10 22:35:43 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-10 22:35:43 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-10 22:35:43 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-10 22:35:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.master_bedroom_tv_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 73, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
