2021-11-05 19:15:31 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:31 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-05 19:15:38 ERROR (SyncWorker_0) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:15:38 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:15:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-05 19:15:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-05 19:15:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 19:15:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 19:15:46 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-11-05 19:15:46 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2021-11-05 19:15:46 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-11-05 19:15:46 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-11-05 19:15:49 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff73b31dc0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-11-05 19:15:52 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the wasbak rechts bulb in the Philips Hue App.
2021-11-05 19:15:54 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2021-11-05 19:15:56 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-05 19:15:56 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-05 19:15:59 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-11-05 19:16:00 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-05 19:16:01 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 645, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 166, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 179, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 155, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 98, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 62, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 211, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1058, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 909, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1051, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-11-05 19:16:02 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-05 19:16:02 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-05 19:16:05 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-05 19:16:05 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:16:05 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-05 19:16:10 ERROR (MainThread) [homeassistant.components.camera] Error while setting up netatmo platform for camera
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('169.254.215.165', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/camera.py", line 58, in async_setup_entry
    await data_handler.register_data_class(
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 187, in register_data_class
    await self.async_fetch_data(data_class_entry)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 144, in async_fetch_data
    await self.data[data_class_entry].async_update()
  File "/usr/local/lib/python3.9/site-packages/pyatmo/camera.py", line 652, in async_update
    await self._async_update_all_camera_urls()
  File "/usr/local/lib/python3.9/site-packages/pyatmo/camera.py", line 662, in _async_update_all_camera_urls
    await self.async_update_camera_urls(camera_id)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/camera.py", line 728, in async_update_camera_urls
    ] = await self._async_check_url(
  File "/usr/local/lib/python3.9/site-packages/pyatmo/camera.py", line 735, in _async_check_url
    resp = await self.auth.async_post_request(url=f"{url}/command/ping")
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 339, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 169.254.215.165:80 ssl:default [Connect call failed ('169.254.215.165', 80)]
2021-11-05 19:16:24 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-05 19:16:24 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-05 19:16:24 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-05 19:16:24 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-05 19:16:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 220, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 381, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 339, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2021-11-05 19:16:34 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-05 19:16:34 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:16:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-05 19:16:39 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:16:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:16:39 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-11-05 19:16:41 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-05 19:17:12 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:17:32 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:17:39 ERROR (SyncWorker_15) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:17:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:18:39 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:18:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:19:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.precip_rate_leuven24_wunderground is taking over 10 seconds
2021-11-05 19:19:39 ERROR (SyncWorker_27) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:19:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:20:39 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:20:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:21:39 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:21:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:22:39 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:22:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:23:39 ERROR (SyncWorker_29) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:23:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:24:39 ERROR (SyncWorker_17) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:24:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:25:39 ERROR (SyncWorker_26) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:25:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:26:39 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:26:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:27:39 ERROR (SyncWorker_15) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:27:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:28:39 ERROR (SyncWorker_24) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:28:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:29:39 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:29:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:30:39 ERROR (SyncWorker_8) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:30:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:31:39 ERROR (SyncWorker_17) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:31:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:32:39 ERROR (SyncWorker_17) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:32:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:33:39 ERROR (SyncWorker_0) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:33:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:34:39 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:34:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:35:33 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:35:39 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:35:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:36:39 ERROR (SyncWorker_10) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:36:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:37:39 ERROR (SyncWorker_3) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:37:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:37:45 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-05 19:38:39 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:38:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:39:39 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:39:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:40:39 ERROR (SyncWorker_17) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:40:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:41:24 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-11-05 19:41:39 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:41:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:42:39 ERROR (SyncWorker_11) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:42:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:43:39 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:43:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:43:55 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-05 19:44:39 ERROR (SyncWorker_11) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:44:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:45:39 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:45:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:46:23 WARNING (SyncWorker_18) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-11-05 19:46:40 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:46:39 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:47:40 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:47:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:48:40 ERROR (SyncWorker_12) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:48:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:49:40 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:49:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:50:40 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:50:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:51:40 ERROR (SyncWorker_15) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:51:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:52:08 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 19:52:40 ERROR (SyncWorker_25) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:52:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:53:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.living_speaker
2021-11-05 19:53:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-11-05 19:53:40 ERROR (SyncWorker_12) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:53:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:53:42 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities camera.netatmo_eikenbos_oprit
2021-11-05 19:54:40 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:54:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:55:12 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.living_speaker
2021-11-05 19:55:40 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:55:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:56:40 ERROR (SyncWorker_12) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:56:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:56:51 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2021-11-05 19:57:10 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2021-11-05 19:57:40 ERROR (SyncWorker_23) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:57:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:58:40 ERROR (SyncWorker_3) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:58:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 19:59:40 ERROR (SyncWorker_0) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 19:59:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:00:40 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:00:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:01:09 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for precip_rate_leuven24_wunderground
2021-11-05 20:01:40 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:01:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:02:40 ERROR (SyncWorker_0) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:02:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:03:40 ERROR (SyncWorker_24) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:03:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:03:48 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-05 20:04:05 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for humidity_leuven24_wunderground
2021-11-05 20:04:05 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for temp_leuven24_wunderground
2021-11-05 20:04:05 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for precip_rate_leuven24_wunderground
2021-11-05 20:04:40 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:04:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:05:40 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:05:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:06:40 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:06:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:07:40 ERROR (SyncWorker_6) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:07:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:08:05 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: https://www.wunderground.com/dashboard/pws/ILEUVE24 failed with [Errno -3] Try again
2021-11-05 20:08:05 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to retrieve data for humidity_leuven24_wunderground
2021-11-05 20:08:05 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: https://www.wunderground.com/dashboard/pws/ILEUVE24 failed with [Errno -3] Try again
2021-11-05 20:08:05 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to retrieve data for temp_leuven24_wunderground
2021-11-05 20:08:40 ERROR (SyncWorker_24) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:08:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:09:40 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:09:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:10:40 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:10:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:11:40 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:11:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:12:40 ERROR (SyncWorker_8) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:12:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:13:40 ERROR (SyncWorker_27) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:13:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:14:40 ERROR (SyncWorker_22) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:14:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:14:51 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-05 20:14:51 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-05 20:14:51 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:14:51 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:15:40 ERROR (SyncWorker_8) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:15:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:16:40 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:16:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:17:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-05 20:17:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-05 20:17:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:17:06 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:17:40 ERROR (SyncWorker_21) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:17:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:18:40 ERROR (SyncWorker_12) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:18:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:19:40 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:19:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:20:40 ERROR (SyncWorker_6) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:20:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:21:40 ERROR (SyncWorker_7) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:21:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:22:40 ERROR (SyncWorker_7) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:22:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:23:40 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:23:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:24:40 ERROR (SyncWorker_13) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:24:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:25:40 ERROR (SyncWorker_10) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:25:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:26:40 ERROR (SyncWorker_27) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:26:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:27:40 ERROR (SyncWorker_26) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:27:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:27:57 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-05 20:28:40 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:28:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:29:40 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:29:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:30:40 ERROR (SyncWorker_19) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Fri, 05 Nov 2021 20:30:40 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-11-05 20:31:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-05 20:31:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-05 20:31:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:31:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:31:24 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-05 20:31:31 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-05 20:31:31 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-05 20:31:31 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-05 20:31:31 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
