2021-10-27 15:00:09 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:09 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:09 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:09 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:09 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:10 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-27 15:00:16 ERROR (SyncWorker_10) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:00:16 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:00:19 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-27 15:00:19 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-27 15:00:19 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-27 15:00:23 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2021-10-27 15:00:23 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2021-10-27 15:00:24 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-10-27 15:00:24 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-10-27 15:00:24 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-10-27 15:00:27 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff7458df40>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-10-27 15:00:31 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the douche bulb in the Philips Hue App.
2021-10-27 15:00:31 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the wasbak rechts bulb in the Philips Hue App.
2021-10-27 15:00:31 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the bad bulb in the Philips Hue App.
2021-10-27 15:00:31 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-10-27 15:00:32 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-27 15:00:32 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-27 15:00:35 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 139, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 152, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 128, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 98, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 62, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 211, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1058, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 909, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1051, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-10-27 15:00:36 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-10-27 15:00:36 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-10-27 15:00:37 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-10-27 15:00:37 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-27 15:01:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:01:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:01:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:01:00 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:01:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 198, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 381, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 339, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2021-10-27 15:01:10 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-10-27 15:01:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-10-27 15:01:15 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-10-27 15:01:17 ERROR (SyncWorker_18) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:01:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:01:19 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-27 15:01:49 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-10-27 15:01:59 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-10-27 15:02:17 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:02:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:03:17 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:03:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:04:17 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:04:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:05:17 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:05:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:06:17 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:06:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:07:17 ERROR (SyncWorker_16) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:07:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:08:17 ERROR (SyncWorker_5) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:08:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:08:25 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-27 15:09:17 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:09:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:10:17 ERROR (SyncWorker_10) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:10:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:10:40 WARNING (SyncWorker_9) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-27 15:11:17 ERROR (SyncWorker_23) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:11:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:12:17 ERROR (SyncWorker_20) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:12:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:13:17 ERROR (SyncWorker_23) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:13:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:13:44 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-27 15:14:17 ERROR (SyncWorker_17) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:14:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:15:17 ERROR (SyncWorker_25) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:15:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:16:17 ERROR (SyncWorker_6) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:16:17 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:16:39 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:16:39 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:16:39 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:17:18 ERROR (SyncWorker_10) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:17:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:18:18 ERROR (SyncWorker_12) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:18:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:19:18 ERROR (SyncWorker_9) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:19:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:20:18 ERROR (SyncWorker_11) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:20:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:20:43 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:21:18 ERROR (SyncWorker_25) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:21:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:22:03 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-27 15:22:18 ERROR (SyncWorker_15) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:22:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:23:18 ERROR (SyncWorker_15) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:23:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:24:18 ERROR (SyncWorker_14) [homeassistant.components.influxdb] InfluxDB bucket is not accessible due to '(401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '2.0.9', 'X-Platform-Error-Code': 'unauthorized', 'Date': 'Wed, 27 Oct 2021 15:24:18 GMT', 'Content-Length': '55'})
HTTP response body: {"code":"unauthorized","message":"unauthorized access"}
'. Please check that the bucket, org and token are correct and that the token has the correct permissions set. Retrying in 60 seconds.
2021-10-27 15:24:39 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:24:39 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-27 15:25:12 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-27 15:25:12 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-27 15:25:12 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
