2022-02-15 17:32:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:19 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-02-15 17:32:28 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-15 17:32:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-15 17:32:31 ERROR (MainThread) [hole] Can not load data from *hole: 192.168.86.101:8081
2022-02-15 17:32:31 WARNING (MainThread) [homeassistant.components.pi_hole] Failed to connect: Can not load data from *hole: 192.168.86.101:8081
2022-02-15 17:32:31 WARNING (MainThread) [homeassistant.config_entries] Config entry 'pihole' for pi_hole integration not ready yet: Can not load data from *hole: 192.168.86.101:8081; Retrying in background
2022-02-15 17:33:13 WARNING (MainThread) [homeassistant.config_entries] Config entry 'GoogleTV' for nfandroidtv integration not ready yet: Failed to connect; Retrying in background
2022-02-15 17:33:15 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call inside the event loop. This is causing stability issues. Please report issue for google_cloud doing blocking calls at homeassistant/components/google_cloud/tts.py, line 212: self._client = texttospeech.TextToSpeechClient()
2022-02-15 17:33:15 ERROR (MainThread) [homeassistant.components.tts] Error setting up platform: google_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 163, in async_setup_platform
    provider = await platform.async_get_engine(
  File "/usr/src/homeassistant/homeassistant/components/google_cloud/tts.py", line 162, in async_get_engine
    return GoogleCloudTTSProvider(
  File "/usr/src/homeassistant/homeassistant/components/google_cloud/tts.py", line 212, in __init__
    self._client = texttospeech.TextToSpeechClient()
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/text_to_speech_client.py", line 141, in __init__
    self.transport = text_to_speech_grpc_transport.TextToSpeechGrpcTransport(
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/transports/text_to_speech_grpc_transport.py", line 60, in __init__
    channel = self.create_channel(address=address, credentials=credentials)
  File "/usr/local/lib/python3.9/site-packages/google/cloud/texttospeech_v1/gapic/transports/text_to_speech_grpc_transport.py", line 87, in create_channel
    return google.api_core.grpc_helpers.create_channel(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 302, in create_channel
    composite_credentials = _create_composite_credentials(
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 236, in _create_composite_credentials
    credentials, _ = google.auth.default(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 544, in default
    credentials, project_id = checker()
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 540, in <lambda>
    lambda: _get_gce_credentials(request),
  File "/usr/local/lib/python3.9/site-packages/google/auth/_default.py", line 274, in _get_gce_credentials
    if _metadata.ping(request=request):
  File "/usr/local/lib/python3.9/site-packages/google/auth/compute_engine/_metadata.py", line 85, in ping
    response = request(
  File "/usr/local/lib/python3.9/site-packages/google/auth/transport/_http_client.py", line 106, in __call__
    connection.request(method, path, body=body, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1290, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 166, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 154, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()` at homeassistant/components/google_cloud/tts.py, line 212: self._client = texttospeech.TextToSpeechClient()
2022-02-15 17:33:17 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff75b2ad00>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2022-02-15 17:33:18 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2022-02-15 17:33:18 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:18 WARNING (MainThread) [aiohue.util] Value {} of type <class 'dict'> is invalid for Device.identify, expected value of type typing.Optional[aiohue.v2.models.feature.IdentifyFeature]
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.outside_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.living_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_amilya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.veranda_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.berging_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.gang_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.badkamer_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.kamer_alunya_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_absolutehumidity (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_heatindex (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_dewpoint (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:21 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.master_bedroom_thermal_perception (<class 'custom_components.thermal_comfort.sensor.SensorThermalComfort'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-15 17:33:22 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-15 17:33:22 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_plafond: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-15 17:33:22 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_plafond: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-15 17:33:22 ERROR (MainThread) [custom_components.powercalc.model_discovery] light.amilya_staande_lamp: Cannot autodiscover model, manufacturer or model unknown from device registry
2022-02-15 17:33:22 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.amilya_staande_lamp: Cannot select a mode (LINEAR, FIXED or LUT, WLED), supply it in the config
2022-02-15 17:33:22 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2022-02-15 17:33:23 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-15 17:33:23 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-15 17:33:23 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-15 17:33:23 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2022-02-15 17:33:25 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 186, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 199, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 167, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2022-02-15 17:33:28 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2022-02-15 17:33:28 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:33:28 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2022-02-15 17:33:28 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:33:29 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2022-02-15 17:33:37 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: audiconnect, googlewifi
2022-02-15 17:33:40 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:33:51 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 17:33:53 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float(default=0) / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float(default=0) ) | round (1) }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 407, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1814, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 523, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 409, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ZeroDivisionError: division by zero
2022-02-15 17:33:53 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ZeroDivisionError: division by zero') while processing template 'Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float(default=0) / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float(default=0) ) | round (1) }}")' for attribute '_attr_native_value' in entity 'sensor.car_range_per_10percent'
2022-02-15 17:34:01 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-15 17:34:01 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:34:01 ERROR (MainThread) [hole] Can not load data from *hole: 192.168.86.101:8081
2022-02-15 17:34:01 WARNING (MainThread) [homeassistant.components.pi_hole] Failed to connect: Can not load data from *hole: 192.168.86.101:8081
2022-02-15 17:34:01 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 233, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 377, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 335, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2022-02-15 17:34:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8ed9056a1a63a8c7f40950d4b361fb19051109e273ea4b7ec9242664650f11f5 from 192.168.86.244
2022-02-15 17:34:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8ed9056a1a63a8c7f40950d4b361fb19051109e273ea4b7ec9242664650f11f5 from 192.168.86.22
2022-02-15 17:34:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8ed9056a1a63a8c7f40950d4b361fb19051109e273ea4b7ec9242664650f11f5 from 192.168.86.246
2022-02-15 17:34:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8ed9056a1a63a8c7f40950d4b361fb19051109e273ea4b7ec9242664650f11f5 from 192.168.86.23
2022-02-15 17:34:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8ed9056a1a63a8c7f40950d4b361fb19051109e273ea4b7ec9242664650f11f5 from 192.168.86.249
2022-02-15 17:34:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2022-02-15 17:34:16 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2022-02-15 17:34:16 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:34:16 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2022-02-15 17:34:16 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2022-02-15 17:34:19 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:34:39 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:34:49 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:34:59 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 17:35:19 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:35:30 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:35:41 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 17:35:41 ERROR (MainThread) [custom_components.audiconnect.audi_account] Error refreshing vehicle data wauzzzge6mb019131
NoneType: None
2022-02-15 17:43:17 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 17:43:23 WARNING (SyncWorker_21) [buienalarm.pybuienalarm] Error fetching data safely: 503 Server Error: Service Unavailable for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2022-02-15 17:43:52 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:44:03 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:44:15 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 17:45:28 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 17:53:17 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 17:54:16 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:54:27 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 17:54:39 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 17:57:28 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:00:08 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'round' got invalid input 'unavailable' when rendering template 'Welkom thuis Madouce! De auto batterij is {{states('sensor.audi_e_tron_sportback_55_state_of_charge') | round (0)}}%.' but no default was specified. Currently 'round' will return 'unavailable', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:01:28 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:01:28 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:01:28 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:04:40 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:04:52 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:05:03 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:13:31 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 18:15:04 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:15:17 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:15:28 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:16:21 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'round' got invalid input 'unavailable' when rendering template 'Welkom thuis Bart! De auto batterij is {{states('sensor.audi_e_tron_sportback_55_state_of_charge') | round (0)}}%.' but no default was specified. Currently 'round' will return 'unavailable', however this template will fail to render in Home Assistant core 2022.1
2022-02-15 18:16:23 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:16:34 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:16:46 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:16:46 ERROR (MainThread) [custom_components.audiconnect.audi_account] Error refreshing vehicle data wauzzzge6mb019131
NoneType: None
2022-02-15 18:24:26 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 18:25:30 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:25:41 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:25:52 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:35:55 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:36:07 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:36:18 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:45:03 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2022-02-15 18:46:20 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:46:31 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:46:42 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:51:57 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 18:56:43 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:56:57 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 18:57:08 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 18:58:57 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:04:57 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:05:32 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:05:57 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:07:10 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:07:21 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:07:32 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 19:10:47 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:12:38 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:13:43 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2022-02-15 19:17:34 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:17:45 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:17:56 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 19:22:42 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:22:53 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2022-02-15 19:23:04 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 'access_token'
2022-02-15 19:24:42 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-15 19:24:43 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: template value should be a string for dictionary value @ data['action'][0]['data']. Got None. (See ?, line ?). 
2022-02-15 19:24:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.veranda_speaker_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 228, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 234, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 143, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 76, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2022-02-15 19:24:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chromebook_bart_madouce_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 228, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 234, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 143, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 76, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2022-02-15 19:24:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.windows_laptop_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 228, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 234, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 143, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 76, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
