2021-10-03 09:47:47 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:47 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-03 09:47:58 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-03 09:47:58 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-03 09:47:58 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 09:47:58 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 09:48:02 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2021-10-03 09:48:03 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-10-03 09:48:03 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-10-03 09:48:03 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-10-03 09:48:05 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-10-03 09:48:06 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: {'api': None, 'code': -1, 'reason': 'Unknown', 'details': 'ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff90b4bcd0>: Failed to establish a new connection: [Errno 113] Host is unreachable'}; Retrying in background
2021-10-03 09:48:07 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID 1632427763962 already exists - ignoring automation.verwarming_aan_en_raam_open_verwarming_uit
2021-10-03 09:48:11 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the douche bulb in the Philips Hue App.
2021-10-03 09:48:11 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the wasbak rechts bulb in the Philips Hue App.
2021-10-03 09:48:11 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the bad bulb in the Philips Hue App.
2021-10-03 09:48:11 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-03 09:48:11 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-03 09:48:12 ERROR (SyncWorker_11) [glocaltokens.client] [Device - Nest Wifi router(id=2f2a9d15-0ae2-4ffe-b6c1-2ef24c742b8a)] local_auth_token must follow the correct format
2021-10-03 09:48:12 ERROR (SyncWorker_11) [glocaltokens.client] [Device - Nest Wifi router(id=e1e5a8d5-d21f-444d-95a9-c76d78c9bc79)] local_auth_token must follow the correct format
2021-10-03 09:48:12 ERROR (SyncWorker_11) [glocaltokens.client] [Device - Nest Wifi router(id=ea3de37c-ca74-4689-8171-1681b2f4f924)] local_auth_token must follow the correct format
2021-10-03 09:48:12 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-03 09:48:13 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 139, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 152, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 128, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1869, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 98, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 62, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 211, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1058, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 909, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1051, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-10-03 09:48:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-10-03 09:48:17 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform buienalarm is taking over 10 seconds.
2021-10-03 09:48:17 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-10-03 09:48:17 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-10-03 09:48:17 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-10-03 09:48:20 WARNING (SyncWorker_10) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 09:48:30 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-03 09:48:40 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2021-10-03 09:48:40 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2021-10-03 09:48:40 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2021-10-03 09:48:42 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-10-03 09:48:58 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-03 09:53:30 WARNING (SyncWorker_0) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 09:58:40 WARNING (SyncWorker_7) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:03:50 WARNING (SyncWorker_3) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:09:00 WARNING (SyncWorker_8) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:12:22 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for precip_rate_leuven24_wunderground
2021-10-03 10:14:10 WARNING (SyncWorker_14) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:15:17 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for precip_rate_leuven24_wunderground
2021-10-03 10:16:15 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for temp_leuven24_wunderground
2021-10-03 10:16:16 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to extract data from HTML for humidity_leuven24_wunderground
2021-10-03 10:19:14 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-03 10:19:20 WARNING (SyncWorker_11) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:20:50 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-03 10:24:30 WARNING (SyncWorker_17) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:28:30 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to update the vehicle position of WAUZZZGE6MB019131: 204, message='No Content', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/cf/v1/Audi/BE/vehicles/WAUZZZGE6MB019131/position')
2021-10-03 10:29:40 WARNING (SyncWorker_6) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:34:15 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-03 10:34:15 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-03 10:34:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:34:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:34:50 WARNING (SyncWorker_0) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-03 10:35:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-03 10:35:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-03 10:35:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:35:16 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:35:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-03 10:35:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-03 10:35:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:35:23 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-03 10:35:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.master_bedroom_tv_on_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 142, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 59, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2021-10-03 10:35:26 WARNING (Thread-130) [homeassistant.util.executor] Thread[SyncWorker_19] is still running at shutdown: File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/discovery/__init__.py", line 221, in _discover
    netdisco.scan(
  File "/usr/local/lib/python3.9/site-packages/netdisco/discovery.py", line 73, in scan
    self.tellstick.scan()
  File "/usr/local/lib/python3.9/site-packages/netdisco/tellstick.py", line 23, in scan
    self.update()
  File "/usr/local/lib/python3.9/site-packages/netdisco/tellstick.py", line 42, in update
    data, (address, _) = sock.recvfrom(1024)
