2021-10-11 12:30:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:40 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-11 12:30:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-11 12:30:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-11 12:30:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 12:30:48 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 12:30:52 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-10-11 12:30:52 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-10-11 12:30:53 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-10-11 12:30:53 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 8b8f82ade2e454d538c7b1b55e021814b7aa12b9fa3693773bc28dc044af0487 from 192.168.86.34
2021-10-11 12:30:55 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-10-11 12:30:56 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff89be26d0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-10-11 12:31:01 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-11 12:31:02 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the douche bulb in the Philips Hue App.
2021-10-11 12:31:02 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the wasbak rechts bulb in the Philips Hue App.
2021-10-11 12:31:02 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the bad bulb in the Philips Hue App.
2021-10-11 12:31:02 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the Amilya plafond 2 bulb in the Philips Hue App.
2021-10-11 12:31:02 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the Amilya plafond 1 bulb in the Philips Hue App.
2021-10-11 12:31:03 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-11 12:31:03 ERROR (SyncWorker_2) [glocaltokens.client] [Device - Nest Wifi router(id=2f2a9d15-0ae2-4ffe-b6c1-2ef24c742b8a)] local_auth_token must follow the correct format
2021-10-11 12:31:03 ERROR (SyncWorker_2) [glocaltokens.client] [Device - Nest Wifi router(id=e1e5a8d5-d21f-444d-95a9-c76d78c9bc79)] local_auth_token must follow the correct format
2021-10-11 12:31:03 ERROR (SyncWorker_2) [glocaltokens.client] [Device - Nest Wifi router(id=ea3de37c-ca74-4689-8171-1681b2f4f924)] local_auth_token must follow the correct format
2021-10-11 12:31:04 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-10-11 12:31:06 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 618, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 139, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 152, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 128, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 98, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 62, in compile
    return cp._cached_css_compile(pattern, namespaces, custom, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 211, in _cached_css_compile
    CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1058, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 909, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1051, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-10-11 12:31:06 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-10-11 12:31:32 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:31:32 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.tv_living_on_today') | float * 0.085 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:31:32 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:31:32 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.master_bedroom_TV_on_today') | float * 0.063 | round(3) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:31:37 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-11 12:31:37 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 198, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 381, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 339, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2021-10-11 12:31:46 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2021-10-11 12:31:46 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miio_fan is taking over 10 seconds.
2021-10-11 12:31:47 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2021-10-11 12:31:48 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-10-11 12:31:49 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-11 12:35:56 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:41:02 WARNING (SyncWorker_14) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 12:43:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:43:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_kamer_alunya_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 12:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 12:59:23 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:01:02 WARNING (SyncWorker_9) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 13:07:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 13:07:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_kamer_alunya_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 13:11:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 13:11:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 13:11:06 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unknown' when rendering template '{{ states('sensor.gram_badkamer_diff_outside') | float >= 1 }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2021.12
2021-10-11 13:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_veranda_bart_en_madouce_2] 🪟 ramen - sluit raam veranda (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_veranda_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_veranda_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:20:01 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:21:02 WARNING (SyncWorker_6) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 13:21:27 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-11 13:22:01 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:34:00 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:34:25 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-11 13:34:41 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:34:46 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-11 13:41:02 WARNING (SyncWorker_12) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 13:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 13:48:47 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 13:53:02 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 13:55:40 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-11 13:58:25 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:01:02 WARNING (SyncWorker_2) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 14:04:20 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-10-11 14:10:49 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:17:44 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 14:21:02 WARNING (SyncWorker_11) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 14:26:02 WARNING (SyncWorker_0) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 14:29:12 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:30:48 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-10-11 14:32:41 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 14:38:32 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 14:41:02 WARNING (SyncWorker_2) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 14:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 14:45:10 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 14:47:54 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'operationState'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 284, in structure_systems
    sensitive_info = await self.get_sensitive_info(system_id=this_system["id"], station_ids=station_ids)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 616, in get_sensitive_info
    status = status["operationState"]
KeyError: 'operationState'
2021-10-11 14:51:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.precip_total_leuven24_wunderground is taking over 10 seconds
2021-10-11 14:51:17 ERROR (MainThread) [homeassistant.components.rest.data] Error fetching data: https://www.wunderground.com/dashboard/pws/ILEUVE24 failed with 
2021-10-11 14:51:17 ERROR (MainThread) [homeassistant.components.scrape.sensor] Unable to retrieve data for precip_total_leuven24_wunderground
2021-10-11 14:54:43 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-10-11 14:57:25 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 15:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:01:02 WARNING (SyncWorker_6) [buienalarm.pybuienalarm] Error fetching data safely: 502 Server Error: Bad Gateway for url: https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=50.878800118427755&lon=4.749415398691782&region=nl&unit=mm%2Fu
2021-10-11 15:04:44 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 15:08:16 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 15:11:05 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 15:13:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] 🪟 ramen - open raam kamer Amilya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] 🪟 ramen - open raam living room (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] 🪟 ramen - open raam kamer Alunya (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_amilya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_amilya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_living_room_bart_en_madouce_2] Error while executing automation automation.ramen_open_raam_living_room_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:15:00 ERROR (MainThread) [homeassistant.components.automation.ramen_open_raam_kamer_alunya_bart_en_madouce] Error while executing automation automation.ramen_open_raam_kamer_alunya_bart_en_madouce: Unable to find service script.notify_bart_windows
2021-10-11 15:16:12 WARNING (SyncWorker_14) [buienalarm.pybuienalarm] Error fetching data safely: HTTPSConnectionPool(host='cdn-secure.buienalarm.nl', port=443): Read timed out. (read timeout=10.0)
2021-10-11 15:16:46 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.veranda_speaker_2
2021-10-11 15:18:14 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-11 15:20:13 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-11 15:20:21 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-10-11 15:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:30:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:31:41 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 289, in structure_systems
    for this_station in system_metrics.get("stationMetrics"):
TypeError: 'NoneType' object is not iterable
2021-10-11 15:42:43 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-10-11 15:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 15:45:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 15:51:28 ERROR (MainThread) [custom_components.googlewifi] Unexpected error fetching GoogleWifi data: 'operationState'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/googlewifi/__init__.py", line 171, in _async_update_data
    system_data = await self.api.get_systems()
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 191, in get_systems
    return await self.structure_systems(response)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 284, in structure_systems
    sensitive_info = await self.get_sensitive_info(system_id=this_system["id"], station_ids=station_ids)
  File "/usr/local/lib/python3.9/site-packages/googlewifi/__init__.py", line 616, in get_sensitive_info
    status = status["operationState"]
KeyError: 'operationState'
2021-10-11 16:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] 🪟 ramen - sluit raam master bedroom (Bart en Madouce): Error executing script. Service not found for call_service at pos 1: Unable to find service script.notify_bart_windows
2021-10-11 16:00:00 ERROR (MainThread) [homeassistant.components.automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2] Error while executing automation automation.ramen_sluit_raam_master_bedroom_bart_en_madouce_2: Unable to find service script.notify_bart_windows
2021-10-11 16:13:22 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-11 16:13:22 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-11 16:13:22 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 16:13:22 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 16:13:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-10-11 16:13:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: [title] is an invalid option for [automation]. Check: automation->action->1->title. (See ?, line ?). 
2021-10-11 16:13:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 16:13:29 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-10-11 16:13:29 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.master_bedroom_tv_on_today fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 60, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
