2021-11-28 11:26:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration monitor_docker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration huesyncbox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration thermal_comfort which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration xiaomi_miio_fan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_10) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration deepstack_face which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_8) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration googlewifi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:34 WARNING (SyncWorker_7) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-28 11:26:41 ERROR (SyncWorker_7) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff73871700>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][1]['platform']. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-28 11:26:45 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-28 11:26:50 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2021-11-28 11:26:50 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2021-11-28 11:26:51 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.28; Retrying in background in 30 seconds
2021-11-28 11:26:51 WARNING (MainThread) [homeassistant.components.fan] Platform xiaomi_miio_fan not ready yet: Unable to discover the device 192.168.86.29; Retrying in background in 30 seconds
2021-11-28 11:26:52 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2021-11-28 11:26:52 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2021-11-28 11:26:54 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.86.83' for synology_dsm integration not ready yet: ConnectionError = <urllib3.connection.HTTPSConnection object at 0xffff6a744dc0>: Failed to establish a new connection: [Errno 113] Host is unreachable; Retrying in background
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'timestamp_custom' got invalid input 'None' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-28 11:26:57 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'timestamp_custom' got invalid input 'None' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden'
2021-11-28 11:26:57 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'as_timestamp' got invalid input '' when rendering template 'sinds {{ as_timestamp(states[config.entity].last_changed) | timestamp_custom('%H:%M', True) }} - {{ (as_timestamp(now()) - as_timestamp(states[config.entity].last_changed)) | timestamp_custom('%H:%M', False) }} geleden' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:26:57 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-28 11:26:57 WARNING (Thread-2) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering or compiling ''
2021-11-28 11:27:02 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-28 11:27:02 WARNING (MainThread) [homeassistant.components.select] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-28 11:27:02 WARNING (MainThread) [homeassistant.components.integration.sensor] Could not restore last state: [<class 'decimal.ConversionSyntax'>]
2021-11-28 11:27:03 WARNING (MainThread) [homeassistant.components.hue.light] Please check for software updates of the douche bulb in the Philips Hue App.
2021-11-28 11:27:03 WARNING (MainThread) [homeassistant.components.energy.sensor] Found unexpected state_class None for sensor.tv_energy
2021-11-28 11:27:04 ERROR (MainThread) [custom_components.powercalc.sensors.power] Skipping sensor setup light.buiten: ('No lookup file found for mode', 'brightness')
2021-11-28 11:27:05 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:27:05 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-28 11:27:05 WARNING (MainThread) [homeassistant.config_entries] Config entry 'OnHub' for upnp integration not ready yet; Retrying in background
2021-11-28 11:27:06 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-28 11:27:06 WARNING (MainThread) [homeassistant.components.sensor] Platform netatmo not ready yet: None; Retrying in background in 30 seconds
2021-11-28 11:27:07 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform scrape is taking over 10 seconds.
2021-11-28 11:27:10 ERROR (MainThread) [homeassistant.components.sensor] scrape: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 166, in async_update
    await self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 179, in _async_update_from_rest_data
    value = await self.hass.async_add_executor_job(self._extract_value)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 155, in _extract_value
    tag = raw_data.select(self._select)[self._index]
  File "/usr/local/lib/python3.9/site-packages/bs4/element.py", line 1949, in select
    results = soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 144, in select
    return compile(select, namespaces, flags, **kwargs).select(tag, limit)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/__init__.py", line 67, in compile
    return cp._cached_css_compile(pattern, ns, cs, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 218, in _cached_css_compile
    CSSParser(
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1159, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 985, in parse_selectors
    key, m = next(iselector)
  File "/usr/local/lib/python3.9/site-packages/soupsieve/css_parser.py", line 1152, in selector_iter
    raise SelectorSyntaxError(msg, self.pattern, index)
soupsieve.util.SelectorSyntaxError: Invalid character '<' position 0
  line 1:
<span _ngcontent-app-root-c173="">Offline</span>
^
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-28 11:27:10 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:27:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-28 11:27:19 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed, trying again in 10 seconds
2021-11-28 11:27:30 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Login to Audi service failed: 503, message='Service Unavailable', url=URL('https://app-api.live-my.audi.com/azs/v1/token')
2021-11-28 11:27:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:27:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:27:40 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 398, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 514, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 400, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ZeroDivisionError: division by zero
2021-11-28 11:27:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:27:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:27:40 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ZeroDivisionError: division by zero') while processing template 'Template("{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}")' for attribute '_attr_native_value' in entity 'sensor.car_range_per_10percent'
2021-11-28 11:27:49 ERROR (SyncWorker_9) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff5fdbadf0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-28 11:27:49 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-28 11:27:49 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:27:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 220, in register_webhook
    await hass.data[DOMAIN][entry.entry_id][AUTH].async_addwebhook(webhook_url)
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 381, in async_addwebhook
    resp = await self.async_post_request(WEBHOOK_URL_ADD, {"url": webhook_url})
  File "/usr/local/lib/python3.9/site-packages/pyatmo/auth.py", line 339, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2021-11-28 11:28:02 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-28 11:28:03 WARNING (MainThread) [homeassistant.components.buienradar.util] Unable to retrieve json data from Buienradar(Msg: , status: None,)
2021-11-28 11:28:03 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1
2021-11-28 11:28:03 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-11-28 11:28:03 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.google_server is taking over 10 seconds
2021-11-28 11:28:03 WARNING (MainThread) [homeassistant.components.media_player] Updating huesyncbox media_player took longer than the scheduled update interval 0:00:02
2021-11-28 11:28:03 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:28:03 WARNING (MainThread) [homeassistant.components.media_player] Updating dlna_dmr media_player took longer than the scheduled update interval 0:00:10
2021-11-28 11:28:05 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 500
2021-11-28 11:28:06 ERROR (MainThread) [custom_components.googlewifi] Error fetching GoogleWifi data: Error connecting to GoogleWifi: 
2021-11-28 11:28:07 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:28:09 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2021-11-28 11:28:22 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:28:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:28:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:28:49 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff48a21490>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-28 11:28:57 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:29:12 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:29:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:29:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:29:49 ERROR (SyncWorker_14) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff5b404490>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-28 11:30:37 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating ping binary_sensor took longer than the scheduled update interval 0:00:05
2021-11-28 11:30:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:30:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:30:49 ERROR (SyncWorker_10) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff59cd3fa0>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2021-11-28 11:31:40 WARNING (MainThread) [haffmpeg.tools] Timeout reading image.
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: expected str for dictionary value @ data['from']. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['trigger'][1]['platform']. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Unexpected value for condition: 'None'. Expected and, device, not, numeric_state, or, state, sun, template, time, trigger, zone @ data['condition'][0]. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: required key not provided @ data['action'][4]['domain']. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: must be a value between 0 and 59 for dictionary value @ data['minutes']. Got None. (See ?, line ?). 
2021-11-28 11:31:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:31:40 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'float' got invalid input 'unavailable' when rendering template '{{ (10 * states('sensor.audi_e_tron_sportback_55_primary_engine_range') | float / states('sensor.audi_e_tron_sportback_55_state_of_charge') | float ) | round (1) }}' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.veranda_speaker_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 73, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2021-11-28 11:31:40 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.master_bedroom_tv_aan_vandaag fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 221, in async_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/history_stats/sensor.py", line 227, in _update
    history_list = history.state_changes_during_period(
  File "/usr/src/homeassistant/homeassistant/components/recorder/history.py", line 147, in state_changes_during_period
    with session_scope(hass=hass) as session:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 73, in session_scope
    session = hass.data[DATA_INSTANCE].get_session()
TypeError: 'NoneType' object is not callable
2021-11-28 11:31:49 ERROR (SyncWorker_16) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to '<urllib3.connection.HTTPConnection object at 0xffff5abdde20>: Failed to establish a new connection: [Errno 111] Connection refused'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
